services:
  db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

    depends_on:
      - db

volumes:
  todo-db-data: